=begin
#Crelate API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CrelateClient::JobsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'JobsApi' do
  before do
    # run before each test
    @instance = CrelateClient::JobsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobsApi' do
    it 'should create an instance of JobsApi' do
      expect(@instance).to be_instance_of(CrelateClient::JobsApi)
    end
  end

  # unit tests for public_api_delete_job
  # delete a job
  # 
  # @param job_id identifier
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_delete_job test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_delete_job_attachment
  # delete an attachment for a job
  # 
  # @param job_id job identifier
  # @param attachment_id attachment identifier
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_delete_job_attachment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_delete_job_contact
  # delete a contact from a job for the recruiting workflow
  # 
  # @param job_id 
  # @param contact_id 
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_delete_job_contact test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_delete_job_note
  # delete a note for a job
  # 
  # @param job_id identifier
  # @param note_id 
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_delete_job_note test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_delete_job_task
  # delete a task for a job
  # 
  # @param job_id 
  # @param task_id identifier
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_delete_job_task test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_get_job
  # retrieve a job
  # 
  # @param job_id identifier
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [PublicApiGetJobResponse]
  describe 'public_api_get_job test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_get_job_attachment
  # get content for a specific attachment for a job
  # 
  # @param job_id identifier
  # @param attachment_id attachment identifier
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_get_job_attachment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_get_job_attachments
  # get all attachment metadata for a company
  # 
  # @param job_id identifier
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [PublicApiAttachmentResponseList]
  describe 'public_api_get_job_attachments test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_get_job_contacts
  # get contacts associated with job
  # 
  # @param job_id contact identifier
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [Array<PublicApiGetJobContact>]
  describe 'public_api_get_job_contacts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_get_job_note
  # get a note for a contact
  # 
  # @param job_id identifier
  # @param note_id 
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [PublicApiGetNoteResponse]
  describe 'public_api_get_job_note test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_get_job_placements
  # Get placements associated with a job  Please Note: TimeToFill is the amount of Days it took to fill the position
  # 
  # @param job_id id for job
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :skip skip number of records, default 0
  # @option opts [Integer] :take retrieve x amount of records, limit 500, default 50
  # @return [PublicApiPlacementResponseList]
  describe 'public_api_get_job_placements test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_get_job_task
  # get a task for a job
  # 
  # @param job_id 
  # @param task_id identifier
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [PublicApiGetTaskResponse]
  describe 'public_api_get_job_task test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_get_jobs
  # retrieve a list of jobs updated within a certain time frame
  # 
  # @param modified modified within x number of minutes ago
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :skip skip number of records, default 0
  # @option opts [Integer] :take retrieve x amount of records, limit 500, default 50
  # @option opts [String] :sales_workflow_item_status_id id of sales workflow item status
  # @option opts [String] :workflow_name name of sales workflow item status
  # @return [PublicApiGetJobListResponse]
  describe 'public_api_get_jobs test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_post_job
  # create a job
  # 
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [PublicApiIdResponse]
  describe 'public_api_post_job test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_post_job_attachment
  # add an attachment to a job
  # 
  # @param job_id identifier
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [PublicApiIdResponse]
  describe 'public_api_post_job_attachment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_post_job_contact
  # move a contact into a job for the first time
  # 
  # @param job_id identifier
  # @param contact_id identifier
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [PublicApiIdResponse]
  describe 'public_api_post_job_contact test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_post_job_note
  # create a note for a job
  # 
  # @param job_id identifier
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [PublicApiIdResponse]
  describe 'public_api_post_job_note test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_post_job_task
  # create a task for a job
  # 
  # @param job_id 
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [PublicApiIdResponse]
  describe 'public_api_post_job_task test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_put_job
  # update a job
  # Replaces all fields. To partially update a job, first retrieve  it using the GET method, apply changes and submit to the PUT method.
  # @param job_id identifier
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_put_job test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_put_job_contact_status
  # update job stage for a contact
  # 
  # @param job_id job identifier
  # @param contact_id contact identifier
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_put_job_contact_status test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_put_job_note
  # update a note for a job
  # 
  # @param job_id identifier
  # @param note_id 
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_put_job_note test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_put_job_task
  # update a task for a job
  # 
  # @param job_id 
  # @param task_id identifier
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_put_job_task test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
