=begin
#Crelate API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CrelateClient::TasksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TasksApi' do
  before do
    # run before each test
    @instance = CrelateClient::TasksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TasksApi' do
    it 'should create an instance of TasksApi' do
      expect(@instance).to be_instance_of(CrelateClient::TasksApi)
    end
  end

  # unit tests for public_api_delete_task
  # delete a task
  # 
  # @param task_id identifier
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_delete_task test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_get_task
  # retrieve a task
  # 
  # @param task_id identifier
  # @param api_key crelate api key
  # @param [Hash] opts the optional parameters
  # @return [PublicApiGetTaskResponse]
  describe 'public_api_get_task test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_post_task
  # create a task
  # 
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [PublicApiIdResponse]
  describe 'public_api_post_task test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_put_task
  # update a task
  # Replaces all fields. To partially update a task, first retrieve  it using the GET method, apply changes and submit to the PUT method.
  # @param task_id 
  # @param api_key crelate api key
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'public_api_put_task test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
