=begin
#Crelate API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module CrelateClient

  class PublicApiAttachmentResponse
    attr_accessor :content_length

    attr_accessor :content_type

    attr_accessor :created_by_id

    attr_accessor :created_by_name

    attr_accessor :created_on

    attr_accessor :file_name

    attr_accessor :id

    attr_accessor :modified_by_id

    attr_accessor :modified_by_name

    attr_accessor :modified_on

    attr_accessor :type_id

    attr_accessor :type_name


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'content_length' => :'ContentLength',
        :'content_type' => :'ContentType',
        :'created_by_id' => :'CreatedBy_Id',
        :'created_by_name' => :'CreatedBy_Name',
        :'created_on' => :'CreatedOn',
        :'file_name' => :'FileName',
        :'id' => :'Id',
        :'modified_by_id' => :'ModifiedBy_Id',
        :'modified_by_name' => :'ModifiedBy_Name',
        :'modified_on' => :'ModifiedOn',
        :'type_id' => :'Type_Id',
        :'type_name' => :'Type_Name'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'content_length' => :'Integer',
        :'content_type' => :'String',
        :'created_by_id' => :'String',
        :'created_by_name' => :'String',
        :'created_on' => :'DateTime',
        :'file_name' => :'String',
        :'id' => :'String',
        :'modified_by_id' => :'String',
        :'modified_by_name' => :'String',
        :'modified_on' => :'DateTime',
        :'type_id' => :'String',
        :'type_name' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'ContentLength')
        self.content_length = attributes[:'ContentLength']
      end

      if attributes.has_key?(:'ContentType')
        self.content_type = attributes[:'ContentType']
      end

      if attributes.has_key?(:'CreatedBy_Id')
        self.created_by_id = attributes[:'CreatedBy_Id']
      end

      if attributes.has_key?(:'CreatedBy_Name')
        self.created_by_name = attributes[:'CreatedBy_Name']
      end

      if attributes.has_key?(:'CreatedOn')
        self.created_on = attributes[:'CreatedOn']
      end

      if attributes.has_key?(:'FileName')
        self.file_name = attributes[:'FileName']
      end

      if attributes.has_key?(:'Id')
        self.id = attributes[:'Id']
      end

      if attributes.has_key?(:'ModifiedBy_Id')
        self.modified_by_id = attributes[:'ModifiedBy_Id']
      end

      if attributes.has_key?(:'ModifiedBy_Name')
        self.modified_by_name = attributes[:'ModifiedBy_Name']
      end

      if attributes.has_key?(:'ModifiedOn')
        self.modified_on = attributes[:'ModifiedOn']
      end

      if attributes.has_key?(:'Type_Id')
        self.type_id = attributes[:'Type_Id']
      end

      if attributes.has_key?(:'Type_Name')
        self.type_name = attributes[:'Type_Name']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          content_length == o.content_length &&
          content_type == o.content_type &&
          created_by_id == o.created_by_id &&
          created_by_name == o.created_by_name &&
          created_on == o.created_on &&
          file_name == o.file_name &&
          id == o.id &&
          modified_by_id == o.modified_by_id &&
          modified_by_name == o.modified_by_name &&
          modified_on == o.modified_on &&
          type_id == o.type_id &&
          type_name == o.type_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [content_length, content_type, created_by_id, created_by_name, created_on, file_name, id, modified_by_id, modified_by_name, modified_on, type_id, type_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CrelateClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
